#!/bin/busybox sh

L(){
    echo -e "\033[33m$@\033[0;0m"
}
# UART MAIN CONSOLE linux/android
export SERIAL_CONSOLE=android

init(){
    mkdir proc sys linux
    mount -t proc none /proc
    mount -t sysfs none /sys
    mdev -s
    mount -t ext4 /dev/mmcblk0p7 /linux
    # uncoment if you want terminal before boot, Ctrl+D to continue
    #busybox getty -L -nl /bin/sh 115200 /dev/ttyMT0 linux

    if [ $SERIAL_CONSOLE == linux ] && grep '^\s*start\s\+console' android/init.rc; then
        L "Disabling android console"
        sed -i 's/^\s*start\s\+console/#start console/' android/init.rc
    fi
    if [ $SERIAL_CONSOLE == android ] && grep '^\s*\#\s*start\s\+console' android/init.rc; then
        L "Enabling android console"
        sed -i 's/^\s*\#\s*start\s\+console/start console/' android/init.rc
    fi

    if [ ! -e /linux/bin/busybox ]; then
        cp -a /bin/busybox /linux/bin/busybox
    fi
    [ -d /linux/android ] || mkdir /linux/android
    mount -t tmpfs none /linux/android
    
    mv android/* linux/android/
    mv emmc@* /linux/android/
    cp -a /init /linux/init_switch
    exec switch_root /linux /init_switch
}


init_switch(){
    if [ -x /android/init ] ; then
        touch /dev/null
        exec chroot /android /init &
        init_wait
    fi

    L "Incorrect init. entering interactive mode."
    exec busybox getty -L -nl /bin/sh 115200 /dev/ttyMT0 linux
}

init_wait(){
    L "Waiting Android init"
    sleep 1
    C=0
    while [ ! -e /android/dev/.coldboot_done ]; do
    #while [ -z "$(grep 'INIT: user build' /android/proc/bootprof)" ]; do
        C=$(($C+1))
        L "wait: $C"
        if [ "$(($C % 10))" = "0" ]; then
            cat /android/proc/bootprof
        fi
        sleep 1
    done
    L "Android init done, mounting sysfs on linux"
    
    #mount -o bind /android/proc /proc
    #mount -o bind /android/sys /sys
    mount -t proc none /proc
    mount -t sysfs none /sys
    mount -o bind /android/dev /dev
    #mount -o bind /android/dev/pts /dev/pts
    mount -t devpts none /dev/pts
    mount -o bind /android/dev/socket /dev/socket
    init_linux
}

init_linux(){
    ifconfig eth0 192.168.1.12 up
    route add default gw 192.168.1.100
    hostname debian
    echo 127.0.0.1 localhost >> /etc/hosts
    busybox date @1592201867 > /dev/null
    if [ ! -x /bin/android ]; then
        cat <<EOF > /bin/android
#!/bin/bash
OLD_PATH=\$PATH
export PATH=/system/sbin:/system/bin:/system/xbin:/sbin:/sbchk
/bin/busybox chroot /android /system/bin/sh
export PATH=\$OLD_PATH
EOF
        chmod +x /bin/android
    fi
    L "Linux init done, telnet at 1234"
    busybox telnetd -l /bin/bash -p 1234 &
    # Serial Terminal
    test $SERIAL_CONSOLE = 'linux' && exec busybox getty -L -nl /bin/bash 115200 /dev/ttyMT0 linux
    L "Not starting tty, console is $SERIAL_CONSOLE"
    exec busybox nc -l -e /bin/sh 
}

format_cache(){
    #mkdir cache system
    #mount -t ext4 /dev/mmcblk0p5 /system
    #mount -t ext4 /dev/mmcblk0p6 /cache
    busybox mkfs.ext2 
}

# call function based on this filename
${0##*/}
