#!/bin/sh

L(){
    echo -e "\e[33m$@\e[0m"
}

init(){
    L "INIT: $0"
    mkdir proc sys linux mnt
    mount -t proc none /proc
    mount -t sysfs none /sys
    mount -t tmpfs none /dev
    # hot plug
    mdev -s

    # mount usr data as linux linux rootfs
    mount -t ext4 -o noatime,errors=panic /dev/mmcblk0p7 /linux
    if [ -e /linux/.NEED_RESIZE ]; then
        umount /linux
        mount -o noatime,errors=panic /dev/mmcblk0p5 /mnt
        /mnt/bin/resize2fs /dev/mmcblk0p7
        #todo get resize2fs binary
        #mount -t ext4 -o noatime,errors=panic /dev/mmcblk0p7 /linux
        #rm -f /linux/.NEED_RESIZE
    fi

    # uncomment if you want terminal before init,ctrl+D to continue
    getty -nl /bin/sh 115200 /dev/ttyMT0 linux

    # Extract android initramfs if contain android initrams
    if [ -e /android.cpio ]; then
        L "Extracting android initramfs.."
        [ -d /linux/android ] || mkdir /linux/android
        cd /linux/android
        cpio -id -F /android.cpio
        chmod 700 * 2>/dev/null
        cd /
    fi    
    # Move kernel generated blockdevice link
    mv emmc@* /linux/android/
    # copy this script to call nextstage
    cp -a $0 /linux/init_multi    

    if [ -x /linux/android/init ] && [ -x /linux/init_multi ]; then
        umount /proc
        umount /sys
        umount /dev
        exec switch_root /linux /init_multi
    fi

    L "Incorrect init. entering interactive mode."
    exec getty -nl /bin/sh 115200 /dev/ttyMT0 linux
}

# your are in switched root
init_multi(){
    L "Starting $0"
    init_wait 2>&1 > /dev/console &
    exec chroot /android /init
}

init_wait(){
    L "Waiting Android init"    
    C=0
    #while [ ! -e /android/dev/.coldboot_done ]; do
    while [ -z "$(grep 'BOOT_Animation:END' /android/proc/bootprof)" ]; do
        C=$(($C+1))
        L "init_wait: $C"
        if [ "$(($C % 10))" = "0" ]; then
            cat /android/proc/bootprof
        fi
        sleep 1
    done
    L "Android init done, mounting sysfs on linux"
    mount -t proc none /proc
    mount -t sysfs none /sys
    mount -o bind /android/dev /dev
    mount -o bind /android/dev/pts /dev/pts
    mount -o bind /android/dev/socket /dev/socket    
    echo "Done linux is ready"
}

# call function based on this filename
${0##*/}
